name: Generate MikroTik RSC File

on:
  schedule:
    - cron: '0 0 1,5,9,13,17,21,25 * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows for manual triggering

jobs:
  generate_rsc_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate MikroTik RSC File
      run: |
        # Variables
        FIREHOL_URL="https://raw.githubusercontent.com/firehol/blocklist-ipsets/refs/heads/master/ip2location_country/ip2location_country_tr.netset"
        OUTPUT_FILE="turkiships.rsc"
        ADDRESS_LIST_NAME="turkiships"
        TIMEOUT="7d"

        # Create or clear the output file
        echo "/ip firewall address-list" > $OUTPUT_FILE

        # Pull the IP list and add each IP to the .rsc file
        curl -s $FIREHOL_URL | grep -E "^[0-9]" | while read -r IP; do
            echo "add address=$IP list=$ADDRESS_LIST_NAME timeout=$TIMEOUT" >> $OUTPUT_FILE
        done

        echo "Generated $OUTPUT_FILE with IP addresses for MikroTik."

    - name: Commit and push changes
      run: |
          git config --local user.email "${GIT_EMAIL}"
          git config --local user.name "ertugrulturan"
          git add Crowdsec_FreeBlacklist.rsc
          git commit -m "Update Crowdsec_FreeBlacklist.rsc"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
